package com.i4season.bkCamera.uirelated.other;

public class FunctionSwitch {
    public static int Angle = 0;
    public static final String App_Vendor_Info = "POWER7";
    public static String Bugly_Key = "aeb2b80e9f";
    public static int DEFAYLT_FILESYSTEM = 4;
    public static boolean DEVICE_AOA = true;
    public static boolean DEVICE_OTG = false;
    public static int DEVICE_REGIST_PRIORITY = 2;
    public static boolean DEVICE_VIRTUAL = true;
    public static boolean IS_FBPRO = false;
    public static boolean IS_ROTING_90 = true;
    public static boolean IS_VOICE_DEVICE = false;
    public static final int LOCAL_DEVICE = 3;
    public static boolean Lic_Need_Online_Burning = false;
    public static final boolean Lic_Online_Burning = true;
    public static final String Online_Burning_Get_Lic_Url = "https://lic.simicloud.com/api/nto/miss?";
    public static final int REMOTE_DEVICE = 0;
    public static boolean ROOTDIR_ONLYONE_AND_ACCEPT_NEXT = true;
    public static final int STORAGE_DEVICE = 2;
    public static boolean SUPPORT_REMOTE_DEVICE = true;
    public static boolean SUPPORT_STORAGE_DEVICE = true;
    public static boolean SUPPORT_WIFI_DEVICE = true;
    public static boolean VOICE_SWITCH = false;
    public static final int WIFI_DEVICE = 1;
    public static int angleValue = 0;
    public static final String authorities = "";
    public static boolean chromecast_function_switch = false;
    public static int col = 0;
    public static boolean currentIsOnline = true;
    public static String deveceWifiSsid = null;
    public static String deviceModleName = null;
    public static String dialogTag = null;
    public static boolean dlna_push_function_switch = true;
    public static boolean isBindFaild = false;
    public static boolean isCanGetSsid = false;
    public static boolean isCheckError = false;
    public static boolean isOffline = false;
    public static String mCurrentDeviceSsid = "";
    public static String mItemRecordSsid = "";
    public static int offsetValue = 0;
    public static String phone_about_QQ1 = "2880652927";
    public static String phone_about_QQ2 = "2880116255";
    public static String phone_about_QQs = "463773262";
    public static String phone_about_Tel = "400–1166–968";
    public static String phone_about_link_url = "http://www.i4season.com/html/index.html";
    public static String phone_about_qq1_url = "mqqwpa://im/chat?chat_type=wpa&uin=31545465454";
    public static String phone_about_qq2_url = "mqqwpa://im/chat?chat_type=wpa&uin=2880116255";
    public static String phone_about_qqskey = "Md-dEaxPtHpPKDbI4nMWNiY6Vub4nzbV";
    public static final String privacyContentURL = "file:///android_asset/privacy/privacy_cn.html";
    public static final String privacyContentURL_en = "file:///android_asset/privacy/privacy_en.html";
    public static boolean restart = false;
    public static int row = 0;
    public static boolean support_AC3_DTS = false;
    public static final String termsOfServiceURL_cn = "file:///android_asset/service/service_cn.html";
    public static final String termsOfServiceURL_en = "file:///android_asset/service/service_en.html";
}
